import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";
// NOTE: generated by `stellar contract bindings typescript` (v28 CLI, SDK 27
// spec) and lightly patched to compile under the backend's strict tsconfig
// (removed browser window shim, dropped unavailable type exports).




export const Errors = {
  /**
   * A required role or config entry is not set; `initialize` has not run.
   */
  1: {message:"NotInitialized"},
  /**
   * `initialize` was already called.
   */
  2: {message:"AlreadyInitialized"},
  /**
   * No remittance exists with the given id.
   */
  3: {message:"RemittanceNotFound"},
  /**
   * `source_amount` is zero or negative, or exceeds `MAX_AMOUNT`.
   */
  4: {message:"InvalidAmount"},
  /**
   * `expiry` is not in `(now, now + MAX_QUOTE_TTL_SECONDS]`.
   */
  5: {message:"InvalidExpiry"},
  /**
   * `destination_asset` is empty or `expected_destination_amount` is not
   * positive.
   */
  6: {message:"InvalidDestination"},
  /**
   * `corridor` is empty.
   */
  7: {message:"InvalidCorridor"},
  /**
   * `sender == recipient`.
   */
  8: {message:"SelfReference"},
  /**
   * `fund_remittance` was called by an address other than the stored
   * sender.
   */
  9: {message:"SenderMismatch"},
  /**
   * A role-gated function was called by a non-role address. (Host-level
   * `require_auth` failures surface as `Unauthorized` panics instead; this
   * error covers contract-level field checks.)
   */
  10: {message:"Unauthorized"},
  /**
   * The action is not valid in the remittance's current state.
   */
  11: {message:"InvalidState"},
  /**
   * An action that must happen before business expiry was attempted after
   * it.
   */
  12: {message:"RemittanceExpired"},
  /**
   * `fund_remittance` on a remittance that has not been created with funds
   * locked (used by `refund` on a `Created` record).
   */
  13: {message:"NotFunded"},
  /**
   * `authorize_settlement` fields do not match the committed remittance.
   */
  14: {message:"SettlementMismatch"},
  /**
   * The corridor is administratively paused.
   */
  15: {message:"CorridorPaused"},
  /**
   * A fee rate exceeds `MAX_FEE_BPS` or the legs sum to more than
   * `MAX_FEE_BPS`.
   */
  16: {message:"FeeBpsOutOfRange"},
  /**
   * A checked arithmetic operation overflowed or underflowed.
   */
  17: {message:"Overflow"},
  /**
   * The remittance-id counter has reached `u64::MAX`. Ids never wrap.
   */
  18: {message:"CounterExhausted"},
  /**
   * The token contract rejected a transfer (insufficient balance, issuer
   * freeze, authorization refused, ...). The token's internal discriminant
   * is intentionally discarded; the diagnostic is visible in the failed
   * transaction's `diagnosticEvents`.
   */
  19: {message:"TokenTransferFailed"},
  /**
   * The `source_asset` address does not resolve to a deployed token
   * contract. No funds moved.
   */
  20: {message:"TokenMissing"}
}

/**
 * Lifecycle state of a remittance.
 * 
 * `Expired` is a *derived* state: it is never persisted. It is computed on
 * read (and reported by `status_of`) for any pre-authorization state whose
 * business `expiry` has passed. Terminal stored states are `Released` and
 * `Refunded`.
 */
export enum Status {
  Created = 0,
  Funded = 1,
  Processing = 2,
  SettlementAuthorized = 3,
  Released = 4,
  Refunded = 5,
  Expired = 6,
}

/**
 * Storage keys.
 * 
 * Instance storage carries contract configuration: roles, the global fee
 * config and per-corridor pause flags. Those must **never** expire silently —
 * a corridor pause that archived itself would silently re-enable a corridor —
 * so they live in instance storage, which is re-extended on every mutating
 * call.
 * 
 * Persistent storage carries the per-remittance records and the two
 * monotonic counters' mirrors used for id allocation.
 */
export type DataKey = {tag: "Admin", values: void} | {tag: "SettlementOracle", values: void} | {tag: "FeeOperator", values: void} | {tag: "FeeConfig", values: void} | {tag: "PausedCorridor", values: readonly [Buffer]} | {tag: "NextId", values: void} | {tag: "Count", values: void} | {tag: "Remittance", values: readonly [u64]};


/**
 * The fee configuration in force for a single remittance.
 * 
 * Snapshotted into [`Remittance::fees`] at creation so release fees are
 * deterministic and auditable regardless of later global configuration
 * changes.
 */
export interface FeeConfig {
  /**
 * Optional anchor/payout-provider fee in basis points. Zero when the
 * corridor has no separate anchor leg.
 */
anchor_bps: u32;
  /**
 * Treasury that receives the anchor fee on release.
 */
anchor_treasury: string;
  /**
 * Corridor/operator fee in basis points.
 */
corridor_bps: u32;
  /**
 * Treasury that receives the corridor fee on release.
 */
corridor_treasury: string;
  /**
 * Platform fee in basis points (1/100 of a percent).
 */
platform_bps: u32;
  /**
 * Treasury that receives the platform fee on release.
 */
platform_treasury: string;
}


/**
 * One remittance commitment.
 */
export interface Remittance {
  /**
 * Time the oracle authorized settlement.
 */
authorized_at: Option<u64>;
  /**
 * Corridor identifier (e.g. `USDC_NGN`). Used by corridor policy and
 * quote integrity.
 */
corridor: Buffer;
  /**
 * Creation time (Unix seconds).
 */
created_at: u64;
  /**
 * Destination payout currency/asset the oracle must attest to (e.g.
 * `NGN`). Off-chain denomination — see `expected_destination_amount`.
 */
destination_asset: Buffer;
  /**
 * Expected destination payout amount the oracle must attest to.
 */
expected_destination_amount: i128;
  /**
 * Business expiry (Unix seconds). Quote integrity and corridor deadlines
 * are enforced against this timestamp; storage TTL is independent.
 */
expiry: u64;
  /**
 * Immutable fee terms this remittance was committed under.
 */
fees: FeeConfig;
  funded_at: Option<u64>;
  /**
 * Monotonic, never-reused identifier.
 */
id: u64;
  /**
 * SHA-256 commitment to the off-chain quote this remittance was priced
 * from. Binds authorization to the exact quote the sender accepted.
 */
quote_hash: Buffer;
  /**
 * The address the escrowed asset is paid to on release. Fixed at
 * creation — recipient substitution is structurally impossible.
 */
recipient: string;
  /**
 * The party whose asset is escrowed. Signs the create; the only party
 * that may fund; the only recipient of a refund.
 */
sender: string;
  /**
 * Time of release or refund (terminal events).
 */
settled_at: Option<u64>;
  /**
 * Gross escrowed amount, in stroops. Fees are carved out of this amount
 * at release; the remainder goes to `recipient`.
 */
source_amount: i128;
  /**
 * SEP-41 / Stellar Asset Contract token address being escrowed.
 */
source_asset: string;
  status: Status;
}


/**
 * What `release` paid out. Returned so the backend can reconcile the escrow
 * payout leg-by-leg without re-deriving the fee math.
 */
export interface ReleaseSummary {
  anchor_fee: i128;
  corridor_fee: i128;
  platform_fee: i128;
  /**
 * Net amount paid to the recipient.
 */
recipient_amount: i128;
}











export interface Client {
  /**
   * Construct and simulate a refund transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Refund the full escrowed amount to the sender.
   * 
   * Rules:
   * * `Funded`, before expiry — only the sender (voluntary cancel).
   * * `Processing`, before expiry — only the admin (emergency refund of a
   * stuck corridor). The sender cannot cancel once settlement is in
   * flight, or a corridor that already paid out could be double-paid.
   * * Any `Funded`/`Processing` after business expiry — permissionless;
   * the funds go to the recorded sender regardless of caller.
   * 
   * Refunds never deduct fees.
   */
  refund: ({id}: {id: u64}, options?: MethodOptions) => Promise<AssembledTransaction<Result<i128>>>

  /**
   * Construct and simulate a release transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Release the escrow: fees to their treasuries, the remainder to the
   * recorded recipient.
   * 
   * Permissionless once settlement is authorized — the payout is fully
   * determined by the record, so any caller produces the same result and
   * funds can never be stuck behind a specific party's wallet.
   */
  release: ({id}: {id: u64}, options?: MethodOptions) => Promise<AssembledTransaction<Result<ReleaseSummary>>>

  /**
   * Construct and simulate a version transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  version: (options?: MethodOptions) => Promise<AssembledTransaction<u32>>

  /**
   * Construct and simulate a get_admin transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_admin: (options?: MethodOptions) => Promise<AssembledTransaction<Result<string>>>

  /**
   * Construct and simulate a set_admin transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Rotate the admin role. Requires the current admin's authorization.
   */
  set_admin: ({new_admin}: {new_admin: string}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a status_of transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Effective status including the derived `Expired` state.
   */
  status_of: ({id}: {id: u64}, options?: MethodOptions) => Promise<AssembledTransaction<Result<Status>>>

  /**
   * Construct and simulate a initialize transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * One-time setup. Records the three roles and the global fee
   * configuration. Only callable before any role is set.
   */
  initialize: ({admin, settlement_oracle, fee_operator, platform_treasury, corridor_treasury, anchor_treasury, platform_bps, corridor_bps, anchor_bps}: {admin: string, settlement_oracle: string, fee_operator: string, platform_treasury: string, corridor_treasury: string, anchor_treasury: string, platform_bps: u32, corridor_bps: u32, anchor_bps: u32}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a is_expired transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Whether business expiry has passed for this remittance.
   * 
   * False for `SettlementAuthorized` (the settlement is committed, so the
   * escrow must remain releasable) and for terminal states.
   */
  is_expired: ({id}: {id: u64}, options?: MethodOptions) => Promise<AssembledTransaction<Result<boolean>>>

  /**
   * Construct and simulate a set_fee_bps transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Set all three fee rates at once. Requires the fee operator. Only
   * affects remittances created afterwards (each snapshots its fees).
   */
  set_fee_bps: ({platform_bps, corridor_bps, anchor_bps}: {platform_bps: u32, corridor_bps: u32, anchor_bps: u32}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a get_fee_config transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_fee_config: (options?: MethodOptions) => Promise<AssembledTransaction<Result<FeeConfig>>>

  /**
   * Construct and simulate a get_remittance transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Full remittance state. Read-only; does not extend the entry's TTL.
   */
  get_remittance: ({id}: {id: u64}, options?: MethodOptions) => Promise<AssembledTransaction<Result<Remittance>>>

  /**
   * Construct and simulate a fund_remittance transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Pull `source_amount` of the committed asset from the sender into
   * escrow. Only the recorded sender may fund, only once, and only before
   * business expiry.
   */
  fund_remittance: ({sender, id}: {sender: string, id: u64}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a begin_processing transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Move a funded remittance into corridor processing. Requires the
   * settlement oracle. The sender can no longer cancel.
   */
  begin_processing: ({id}: {id: u64}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a get_fee_operator transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_fee_operator: (options?: MethodOptions) => Promise<AssembledTransaction<Result<string>>>

  /**
   * Construct and simulate a remittance_count transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Total remittances ever created. Ids run `0..count`.
   */
  remittance_count: (options?: MethodOptions) => Promise<AssembledTransaction<u64>>

  /**
   * Construct and simulate a set_fee_operator transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Rotate the fee operator. Requires the current admin.
   */
  set_fee_operator: ({new_operator}: {new_operator: string}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a set_fee_treasury transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Move a fee treasury. Requires the fee operator.
   */
  set_fee_treasury: ({leg, treasury}: {leg: string, treasury: string}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a create_remittance transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Create a remittance commitment.
   * 
   * Everything that matters is fixed here: sender, recipient, escrowed
   * asset and amount, the destination terms the oracle will later attest
   * to, the corridor, the quote hash and the business expiry. The fee
   * configuration is snapshotted.
   * 
   * Returns the new id (monotonic, never reused).
   */
  create_remittance: ({sender, recipient, source_asset, source_amount, destination_asset, expected_destination_amount, corridor, quote_hash, expiry}: {sender: string, recipient: string, source_asset: string, source_amount: i128, destination_asset: Buffer, expected_destination_amount: i128, corridor: Buffer, quote_hash: Buffer, expiry: u64}, options?: MethodOptions) => Promise<AssembledTransaction<Result<u64>>>

  /**
   * Construct and simulate a is_corridor_paused transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Whether a corridor is administratively paused.
   */
  is_corridor_paused: ({corridor}: {corridor: Buffer}, options?: MethodOptions) => Promise<AssembledTransaction<boolean>>

  /**
   * Construct and simulate a set_corridor_paused transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Pause or resume a corridor. Requires the admin. Paused corridors cannot
   * host new remittances; existing ones are unaffected.
   */
  set_corridor_paused: ({corridor, paused}: {corridor: Buffer, paused: boolean}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a authorize_settlement transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Attest that the off-chain settlement was completed exactly as
   * committed.
   * 
   * The oracle re-states the full committed terms (sender, recipient,
   * source asset & amount, destination asset & expected amount, corridor,
   * quote hash and expiry). Any mismatch with the stored commitment is
   * rejected with [`Error::SettlementMismatch`], which binds authorization
   * to the exact quote the sender accepted. Requires the settlement oracle,
   * must happen before business expiry, and only from `Funded` or
   * `Processing`.
   */
  authorize_settlement: ({id, sender, recipient, source_asset, source_amount, destination_asset, expected_destination_amount, corridor, quote_hash, expiry}: {id: u64, sender: string, recipient: string, source_asset: string, source_amount: i128, destination_asset: Buffer, expected_destination_amount: i128, corridor: Buffer, quote_hash: Buffer, expiry: u64}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a extend_remittance_ttl transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Extend a remittance entry's storage TTL. Permissionless — a keeper or
   * indexer may pay rent for any record. Cannot move funds or change
   * state. Returns the number of ledgers the entry is now good for.
   */
  extend_remittance_ttl: ({id}: {id: u64}, options?: MethodOptions) => Promise<AssembledTransaction<Result<u32>>>

  /**
   * Construct and simulate a get_settlement_oracle transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_settlement_oracle: (options?: MethodOptions) => Promise<AssembledTransaction<Result<string>>>

  /**
   * Construct and simulate a set_settlement_oracle transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Rotate the settlement oracle. Requires the current admin.
   */
  set_settlement_oracle: ({new_oracle}: {new_oracle: string}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

}
export class Client extends ContractClient {
  static override async deploy<T = Client>(
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options)
  }
  constructor(public override readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAAAAAAAd5SZWZ1bmQgdGhlIGZ1bGwgZXNjcm93ZWQgYW1vdW50IHRvIHRoZSBzZW5kZXIuCgpSdWxlczoKKiBgRnVuZGVkYCwgYmVmb3JlIGV4cGlyeSDigJQgb25seSB0aGUgc2VuZGVyICh2b2x1bnRhcnkgY2FuY2VsKS4KKiBgUHJvY2Vzc2luZ2AsIGJlZm9yZSBleHBpcnkg4oCUIG9ubHkgdGhlIGFkbWluIChlbWVyZ2VuY3kgcmVmdW5kIG9mIGEKc3R1Y2sgY29ycmlkb3IpLiBUaGUgc2VuZGVyIGNhbm5vdCBjYW5jZWwgb25jZSBzZXR0bGVtZW50IGlzIGluCmZsaWdodCwgb3IgYSBjb3JyaWRvciB0aGF0IGFscmVhZHkgcGFpZCBvdXQgY291bGQgYmUgZG91YmxlLXBhaWQuCiogQW55IGBGdW5kZWRgL2BQcm9jZXNzaW5nYCBhZnRlciBidXNpbmVzcyBleHBpcnkg4oCUIHBlcm1pc3Npb25sZXNzOwp0aGUgZnVuZHMgZ28gdG8gdGhlIHJlY29yZGVkIHNlbmRlciByZWdhcmRsZXNzIG9mIGNhbGxlci4KClJlZnVuZHMgbmV2ZXIgZGVkdWN0IGZlZXMuAAAAAAAGcmVmdW5kAAAAAAABAAAAAAAAAAJpZAAAAAAABgAAAAEAAAPpAAAACwAAAAM=",
        "AAAAAAAAARxSZWxlYXNlIHRoZSBlc2Nyb3c6IGZlZXMgdG8gdGhlaXIgdHJlYXN1cmllcywgdGhlIHJlbWFpbmRlciB0byB0aGUKcmVjb3JkZWQgcmVjaXBpZW50LgoKUGVybWlzc2lvbmxlc3Mgb25jZSBzZXR0bGVtZW50IGlzIGF1dGhvcml6ZWQg4oCUIHRoZSBwYXlvdXQgaXMgZnVsbHkKZGV0ZXJtaW5lZCBieSB0aGUgcmVjb3JkLCBzbyBhbnkgY2FsbGVyIHByb2R1Y2VzIHRoZSBzYW1lIHJlc3VsdCBhbmQKZnVuZHMgY2FuIG5ldmVyIGJlIHN0dWNrIGJlaGluZCBhIHNwZWNpZmljIHBhcnR5J3Mgd2FsbGV0LgAAAAdyZWxlYXNlAAAAAAEAAAAAAAAAAmlkAAAAAAAGAAAAAQAAA+kAAAfQAAAADlJlbGVhc2VTdW1tYXJ5AAAAAAAD",
        "AAAAAAAAAAAAAAAHdmVyc2lvbgAAAAAAAAAAAQAAAAQ=",
        "AAAAAAAAAAAAAAAJZ2V0X2FkbWluAAAAAAAAAAAAAAEAAAPpAAAAEwAAAAM=",
        "AAAAAAAAAEJSb3RhdGUgdGhlIGFkbWluIHJvbGUuIFJlcXVpcmVzIHRoZSBjdXJyZW50IGFkbWluJ3MgYXV0aG9yaXphdGlvbi4AAAAAAAlzZXRfYWRtaW4AAAAAAAABAAAAAAAAAAluZXdfYWRtaW4AAAAAAAATAAAAAQAAA+kAAAACAAAAAw==",
        "AAAAAAAAADdFZmZlY3RpdmUgc3RhdHVzIGluY2x1ZGluZyB0aGUgZGVyaXZlZCBgRXhwaXJlZGAgc3RhdGUuAAAAAAlzdGF0dXNfb2YAAAAAAAABAAAAAAAAAAJpZAAAAAAABgAAAAEAAAPpAAAH0AAAAAZTdGF0dXMAAAAAAAM=",
        "AAAAAAAAAG9PbmUtdGltZSBzZXR1cC4gUmVjb3JkcyB0aGUgdGhyZWUgcm9sZXMgYW5kIHRoZSBnbG9iYWwgZmVlCmNvbmZpZ3VyYXRpb24uIE9ubHkgY2FsbGFibGUgYmVmb3JlIGFueSByb2xlIGlzIHNldC4AAAAACmluaXRpYWxpemUAAAAAAAkAAAAAAAAABWFkbWluAAAAAAAAEwAAAAAAAAARc2V0dGxlbWVudF9vcmFjbGUAAAAAAAATAAAAAAAAAAxmZWVfb3BlcmF0b3IAAAATAAAAAAAAABFwbGF0Zm9ybV90cmVhc3VyeQAAAAAAABMAAAAAAAAAEWNvcnJpZG9yX3RyZWFzdXJ5AAAAAAAAEwAAAAAAAAAPYW5jaG9yX3RyZWFzdXJ5AAAAABMAAAAAAAAADHBsYXRmb3JtX2JwcwAAAAQAAAAAAAAADGNvcnJpZG9yX2JwcwAAAAQAAAAAAAAACmFuY2hvcl9icHMAAAAAAAQAAAABAAAD6QAAAAIAAAAD",
        "AAAAAAAAALZXaGV0aGVyIGJ1c2luZXNzIGV4cGlyeSBoYXMgcGFzc2VkIGZvciB0aGlzIHJlbWl0dGFuY2UuCgpGYWxzZSBmb3IgYFNldHRsZW1lbnRBdXRob3JpemVkYCAodGhlIHNldHRsZW1lbnQgaXMgY29tbWl0dGVkLCBzbyB0aGUKZXNjcm93IG11c3QgcmVtYWluIHJlbGVhc2FibGUpIGFuZCBmb3IgdGVybWluYWwgc3RhdGVzLgAAAAAACmlzX2V4cGlyZWQAAAAAAAEAAAAAAAAAAmlkAAAAAAAGAAAAAQAAA+kAAAABAAAAAw==",
        "AAAAAAAAAIJTZXQgYWxsIHRocmVlIGZlZSByYXRlcyBhdCBvbmNlLiBSZXF1aXJlcyB0aGUgZmVlIG9wZXJhdG9yLiBPbmx5CmFmZmVjdHMgcmVtaXR0YW5jZXMgY3JlYXRlZCBhZnRlcndhcmRzIChlYWNoIHNuYXBzaG90cyBpdHMgZmVlcykuAAAAAAALc2V0X2ZlZV9icHMAAAAAAwAAAAAAAAAMcGxhdGZvcm1fYnBzAAAABAAAAAAAAAAMY29ycmlkb3JfYnBzAAAABAAAAAAAAAAKYW5jaG9yX2JwcwAAAAAABAAAAAEAAAPpAAAAAgAAAAM=",
        "AAAAAAAAAAAAAAAOZ2V0X2ZlZV9jb25maWcAAAAAAAAAAAABAAAD6QAAB9AAAAAJRmVlQ29uZmlnAAAAAAAAAw==",
        "AAAAAAAAAEJGdWxsIHJlbWl0dGFuY2Ugc3RhdGUuIFJlYWQtb25seTsgZG9lcyBub3QgZXh0ZW5kIHRoZSBlbnRyeSdzIFRUTC4AAAAAAA5nZXRfcmVtaXR0YW5jZQAAAAAAAQAAAAAAAAACaWQAAAAAAAYAAAABAAAD6QAAB9AAAAAKUmVtaXR0YW5jZQAAAAAAAw==",
        "AAAAAAAAAJdQdWxsIGBzb3VyY2VfYW1vdW50YCBvZiB0aGUgY29tbWl0dGVkIGFzc2V0IGZyb20gdGhlIHNlbmRlciBpbnRvCmVzY3Jvdy4gT25seSB0aGUgcmVjb3JkZWQgc2VuZGVyIG1heSBmdW5kLCBvbmx5IG9uY2UsIGFuZCBvbmx5IGJlZm9yZQpidXNpbmVzcyBleHBpcnkuAAAAAA9mdW5kX3JlbWl0dGFuY2UAAAAAAgAAAAAAAAAGc2VuZGVyAAAAAAATAAAAAAAAAAJpZAAAAAAABgAAAAEAAAPpAAAAAgAAAAM=",
        "AAAAAAAAAHNNb3ZlIGEgZnVuZGVkIHJlbWl0dGFuY2UgaW50byBjb3JyaWRvciBwcm9jZXNzaW5nLiBSZXF1aXJlcyB0aGUKc2V0dGxlbWVudCBvcmFjbGUuIFRoZSBzZW5kZXIgY2FuIG5vIGxvbmdlciBjYW5jZWwuAAAAABBiZWdpbl9wcm9jZXNzaW5nAAAAAQAAAAAAAAACaWQAAAAAAAYAAAABAAAD6QAAAAIAAAAD",
        "AAAAAAAAAAAAAAAQZ2V0X2ZlZV9vcGVyYXRvcgAAAAAAAAABAAAD6QAAABMAAAAD",
        "AAAAAAAAADNUb3RhbCByZW1pdHRhbmNlcyBldmVyIGNyZWF0ZWQuIElkcyBydW4gYDAuLmNvdW50YC4AAAAAEHJlbWl0dGFuY2VfY291bnQAAAAAAAAAAQAAAAY=",
        "AAAAAAAAADRSb3RhdGUgdGhlIGZlZSBvcGVyYXRvci4gUmVxdWlyZXMgdGhlIGN1cnJlbnQgYWRtaW4uAAAAEHNldF9mZWVfb3BlcmF0b3IAAAABAAAAAAAAAAxuZXdfb3BlcmF0b3IAAAATAAAAAQAAA+kAAAACAAAAAw==",
        "AAAAAAAAAC9Nb3ZlIGEgZmVlIHRyZWFzdXJ5LiBSZXF1aXJlcyB0aGUgZmVlIG9wZXJhdG9yLgAAAAAQc2V0X2ZlZV90cmVhc3VyeQAAAAIAAAAAAAAAA2xlZwAAAAARAAAAAAAAAAh0cmVhc3VyeQAAABMAAAABAAAD6QAAAAIAAAAD",
        "AAAAAAAAATdDcmVhdGUgYSByZW1pdHRhbmNlIGNvbW1pdG1lbnQuCgpFdmVyeXRoaW5nIHRoYXQgbWF0dGVycyBpcyBmaXhlZCBoZXJlOiBzZW5kZXIsIHJlY2lwaWVudCwgZXNjcm93ZWQKYXNzZXQgYW5kIGFtb3VudCwgdGhlIGRlc3RpbmF0aW9uIHRlcm1zIHRoZSBvcmFjbGUgd2lsbCBsYXRlciBhdHRlc3QKdG8sIHRoZSBjb3JyaWRvciwgdGhlIHF1b3RlIGhhc2ggYW5kIHRoZSBidXNpbmVzcyBleHBpcnkuIFRoZSBmZWUKY29uZmlndXJhdGlvbiBpcyBzbmFwc2hvdHRlZC4KClJldHVybnMgdGhlIG5ldyBpZCAobW9ub3RvbmljLCBuZXZlciByZXVzZWQpLgAAAAARY3JlYXRlX3JlbWl0dGFuY2UAAAAAAAAJAAAAAAAAAAZzZW5kZXIAAAAAABMAAAAAAAAACXJlY2lwaWVudAAAAAAAABMAAAAAAAAADHNvdXJjZV9hc3NldAAAABMAAAAAAAAADXNvdXJjZV9hbW91bnQAAAAAAAALAAAAAAAAABFkZXN0aW5hdGlvbl9hc3NldAAAAAAAAA4AAAAAAAAAG2V4cGVjdGVkX2Rlc3RpbmF0aW9uX2Ftb3VudAAAAAALAAAAAAAAAAhjb3JyaWRvcgAAAA4AAAAAAAAACnF1b3RlX2hhc2gAAAAAA+4AAAAgAAAAAAAAAAZleHBpcnkAAAAAAAYAAAABAAAD6QAAAAYAAAAD",
        "AAAAAAAAAC5XaGV0aGVyIGEgY29ycmlkb3IgaXMgYWRtaW5pc3RyYXRpdmVseSBwYXVzZWQuAAAAAAASaXNfY29ycmlkb3JfcGF1c2VkAAAAAAABAAAAAAAAAAhjb3JyaWRvcgAAAA4AAAABAAAAAQ==",
        "AAAAAAAAAHtQYXVzZSBvciByZXN1bWUgYSBjb3JyaWRvci4gUmVxdWlyZXMgdGhlIGFkbWluLiBQYXVzZWQgY29ycmlkb3JzIGNhbm5vdApob3N0IG5ldyByZW1pdHRhbmNlczsgZXhpc3Rpbmcgb25lcyBhcmUgdW5hZmZlY3RlZC4AAAAAE3NldF9jb3JyaWRvcl9wYXVzZWQAAAAAAgAAAAAAAAAIY29ycmlkb3IAAAAOAAAAAAAAAAZwYXVzZWQAAAAAAAEAAAABAAAD6QAAAAIAAAAD",
        "AAAAAAAAAe9BdHRlc3QgdGhhdCB0aGUgb2ZmLWNoYWluIHNldHRsZW1lbnQgd2FzIGNvbXBsZXRlZCBleGFjdGx5IGFzCmNvbW1pdHRlZC4KClRoZSBvcmFjbGUgcmUtc3RhdGVzIHRoZSBmdWxsIGNvbW1pdHRlZCB0ZXJtcyAoc2VuZGVyLCByZWNpcGllbnQsCnNvdXJjZSBhc3NldCAmIGFtb3VudCwgZGVzdGluYXRpb24gYXNzZXQgJiBleHBlY3RlZCBhbW91bnQsIGNvcnJpZG9yLApxdW90ZSBoYXNoIGFuZCBleHBpcnkpLiBBbnkgbWlzbWF0Y2ggd2l0aCB0aGUgc3RvcmVkIGNvbW1pdG1lbnQgaXMKcmVqZWN0ZWQgd2l0aCBbYEVycm9yOjpTZXR0bGVtZW50TWlzbWF0Y2hgXSwgd2hpY2ggYmluZHMgYXV0aG9yaXphdGlvbgp0byB0aGUgZXhhY3QgcXVvdGUgdGhlIHNlbmRlciBhY2NlcHRlZC4gUmVxdWlyZXMgdGhlIHNldHRsZW1lbnQgb3JhY2xlLAptdXN0IGhhcHBlbiBiZWZvcmUgYnVzaW5lc3MgZXhwaXJ5LCBhbmQgb25seSBmcm9tIGBGdW5kZWRgIG9yCmBQcm9jZXNzaW5nYC4AAAAAFGF1dGhvcml6ZV9zZXR0bGVtZW50AAAACgAAAAAAAAACaWQAAAAAAAYAAAAAAAAABnNlbmRlcgAAAAAAEwAAAAAAAAAJcmVjaXBpZW50AAAAAAAAEwAAAAAAAAAMc291cmNlX2Fzc2V0AAAAEwAAAAAAAAANc291cmNlX2Ftb3VudAAAAAAAAAsAAAAAAAAAEWRlc3RpbmF0aW9uX2Fzc2V0AAAAAAAADgAAAAAAAAAbZXhwZWN0ZWRfZGVzdGluYXRpb25fYW1vdW50AAAAAAsAAAAAAAAACGNvcnJpZG9yAAAADgAAAAAAAAAKcXVvdGVfaGFzaAAAAAAD7gAAACAAAAAAAAAABmV4cGlyeQAAAAAABgAAAAEAAAPpAAAAAgAAAAM=",
        "AAAAAAAAAMhFeHRlbmQgYSByZW1pdHRhbmNlIGVudHJ5J3Mgc3RvcmFnZSBUVEwuIFBlcm1pc3Npb25sZXNzIOKAlCBhIGtlZXBlciBvcgppbmRleGVyIG1heSBwYXkgcmVudCBmb3IgYW55IHJlY29yZC4gQ2Fubm90IG1vdmUgZnVuZHMgb3IgY2hhbmdlCnN0YXRlLiBSZXR1cm5zIHRoZSBudW1iZXIgb2YgbGVkZ2VycyB0aGUgZW50cnkgaXMgbm93IGdvb2QgZm9yLgAAABVleHRlbmRfcmVtaXR0YW5jZV90dGwAAAAAAAABAAAAAAAAAAJpZAAAAAAABgAAAAEAAAPpAAAABAAAAAM=",
        "AAAAAAAAAAAAAAAVZ2V0X3NldHRsZW1lbnRfb3JhY2xlAAAAAAAAAAAAAAEAAAPpAAAAEwAAAAM=",
        "AAAAAAAAADlSb3RhdGUgdGhlIHNldHRsZW1lbnQgb3JhY2xlLiBSZXF1aXJlcyB0aGUgY3VycmVudCBhZG1pbi4AAAAAAAAVc2V0X3NldHRsZW1lbnRfb3JhY2xlAAAAAAAAAQAAAAAAAAAKbmV3X29yYWNsZQAAAAAAEwAAAAEAAAPpAAAAAgAAAAM=",
        "AAAABAAAAAAAAAAAAAAABUVycm9yAAAAAAAAFAAAAEVBIHJlcXVpcmVkIHJvbGUgb3IgY29uZmlnIGVudHJ5IGlzIG5vdCBzZXQ7IGBpbml0aWFsaXplYCBoYXMgbm90IHJ1bi4AAAAAAAAOTm90SW5pdGlhbGl6ZWQAAAAAAAEAAAAgYGluaXRpYWxpemVgIHdhcyBhbHJlYWR5IGNhbGxlZC4AAAASQWxyZWFkeUluaXRpYWxpemVkAAAAAAACAAAAJ05vIHJlbWl0dGFuY2UgZXhpc3RzIHdpdGggdGhlIGdpdmVuIGlkLgAAAAASUmVtaXR0YW5jZU5vdEZvdW5kAAAAAAADAAAAPWBzb3VyY2VfYW1vdW50YCBpcyB6ZXJvIG9yIG5lZ2F0aXZlLCBvciBleGNlZWRzIGBNQVhfQU1PVU5UYC4AAAAAAAANSW52YWxpZEFtb3VudAAAAAAAAAQAAAA4YGV4cGlyeWAgaXMgbm90IGluIGAobm93LCBub3cgKyBNQVhfUVVPVEVfVFRMX1NFQ09ORFNdYC4AAAANSW52YWxpZEV4cGlyeQAAAAAAAAUAAABOYGRlc3RpbmF0aW9uX2Fzc2V0YCBpcyBlbXB0eSBvciBgZXhwZWN0ZWRfZGVzdGluYXRpb25fYW1vdW50YCBpcyBub3QKcG9zaXRpdmUuAAAAAAASSW52YWxpZERlc3RpbmF0aW9uAAAAAAAGAAAAFGBjb3JyaWRvcmAgaXMgZW1wdHkuAAAAD0ludmFsaWRDb3JyaWRvcgAAAAAHAAAAFmBzZW5kZXIgPT0gcmVjaXBpZW50YC4AAAAAAA1TZWxmUmVmZXJlbmNlAAAAAAAACAAAAEhgZnVuZF9yZW1pdHRhbmNlYCB3YXMgY2FsbGVkIGJ5IGFuIGFkZHJlc3Mgb3RoZXIgdGhhbiB0aGUgc3RvcmVkCnNlbmRlci4AAAAOU2VuZGVyTWlzbWF0Y2gAAAAAAAkAAAC1QSByb2xlLWdhdGVkIGZ1bmN0aW9uIHdhcyBjYWxsZWQgYnkgYSBub24tcm9sZSBhZGRyZXNzLiAoSG9zdC1sZXZlbApgcmVxdWlyZV9hdXRoYCBmYWlsdXJlcyBzdXJmYWNlIGFzIGBVbmF1dGhvcml6ZWRgIHBhbmljcyBpbnN0ZWFkOyB0aGlzCmVycm9yIGNvdmVycyBjb250cmFjdC1sZXZlbCBmaWVsZCBjaGVja3MuKQAAAAAAAAxVbmF1dGhvcml6ZWQAAAAKAAAAOlRoZSBhY3Rpb24gaXMgbm90IHZhbGlkIGluIHRoZSByZW1pdHRhbmNlJ3MgY3VycmVudCBzdGF0ZS4AAAAAAAxJbnZhbGlkU3RhdGUAAAALAAAASUFuIGFjdGlvbiB0aGF0IG11c3QgaGFwcGVuIGJlZm9yZSBidXNpbmVzcyBleHBpcnkgd2FzIGF0dGVtcHRlZCBhZnRlcgppdC4AAAAAAAARUmVtaXR0YW5jZUV4cGlyZWQAAAAAAAAMAAAAd2BmdW5kX3JlbWl0dGFuY2VgIG9uIGEgcmVtaXR0YW5jZSB0aGF0IGhhcyBub3QgYmVlbiBjcmVhdGVkIHdpdGggZnVuZHMKbG9ja2VkICh1c2VkIGJ5IGByZWZ1bmRgIG9uIGEgYENyZWF0ZWRgIHJlY29yZCkuAAAAAAlOb3RGdW5kZWQAAAAAAAANAAAARGBhdXRob3JpemVfc2V0dGxlbWVudGAgZmllbGRzIGRvIG5vdCBtYXRjaCB0aGUgY29tbWl0dGVkIHJlbWl0dGFuY2UuAAAAElNldHRsZW1lbnRNaXNtYXRjaAAAAAAADgAAAChUaGUgY29ycmlkb3IgaXMgYWRtaW5pc3RyYXRpdmVseSBwYXVzZWQuAAAADkNvcnJpZG9yUGF1c2VkAAAAAAAPAAAATEEgZmVlIHJhdGUgZXhjZWVkcyBgTUFYX0ZFRV9CUFNgIG9yIHRoZSBsZWdzIHN1bSB0byBtb3JlIHRoYW4KYE1BWF9GRUVfQlBTYC4AAAAQRmVlQnBzT3V0T2ZSYW5nZQAAABAAAAA5QSBjaGVja2VkIGFyaXRobWV0aWMgb3BlcmF0aW9uIG92ZXJmbG93ZWQgb3IgdW5kZXJmbG93ZWQuAAAAAAAACE92ZXJmbG93AAAAEQAAAEFUaGUgcmVtaXR0YW5jZS1pZCBjb3VudGVyIGhhcyByZWFjaGVkIGB1NjQ6Ok1BWGAuIElkcyBuZXZlciB3cmFwLgAAAAAAABBDb3VudGVyRXhoYXVzdGVkAAAAEgAAAPFUaGUgdG9rZW4gY29udHJhY3QgcmVqZWN0ZWQgYSB0cmFuc2ZlciAoaW5zdWZmaWNpZW50IGJhbGFuY2UsIGlzc3VlcgpmcmVlemUsIGF1dGhvcml6YXRpb24gcmVmdXNlZCwgLi4uKS4gVGhlIHRva2VuJ3MgaW50ZXJuYWwgZGlzY3JpbWluYW50CmlzIGludGVudGlvbmFsbHkgZGlzY2FyZGVkOyB0aGUgZGlhZ25vc3RpYyBpcyB2aXNpYmxlIGluIHRoZSBmYWlsZWQKdHJhbnNhY3Rpb24ncyBgZGlhZ25vc3RpY0V2ZW50c2AuAAAAAAAAE1Rva2VuVHJhbnNmZXJGYWlsZWQAAAAAEwAAAFlUaGUgYHNvdXJjZV9hc3NldGAgYWRkcmVzcyBkb2VzIG5vdCByZXNvbHZlIHRvIGEgZGVwbG95ZWQgdG9rZW4KY29udHJhY3QuIE5vIGZ1bmRzIG1vdmVkLgAAAAAAAAxUb2tlbk1pc3NpbmcAAAAU",
        "AAAAAwAAAQdMaWZlY3ljbGUgc3RhdGUgb2YgYSByZW1pdHRhbmNlLgoKYEV4cGlyZWRgIGlzIGEgKmRlcml2ZWQqIHN0YXRlOiBpdCBpcyBuZXZlciBwZXJzaXN0ZWQuIEl0IGlzIGNvbXB1dGVkIG9uCnJlYWQgKGFuZCByZXBvcnRlZCBieSBgc3RhdHVzX29mYCkgZm9yIGFueSBwcmUtYXV0aG9yaXphdGlvbiBzdGF0ZSB3aG9zZQpidXNpbmVzcyBgZXhwaXJ5YCBoYXMgcGFzc2VkLiBUZXJtaW5hbCBzdG9yZWQgc3RhdGVzIGFyZSBgUmVsZWFzZWRgIGFuZApgUmVmdW5kZWRgLgAAAAAAAAAABlN0YXR1cwAAAAAABwAAAChDb21taXRtZW50IGNyZWF0ZWQ7IG5vIGZ1bmRzIGxvY2tlZCB5ZXQuAAAAB0NyZWF0ZWQAAAAAAAAAAD5gc291cmNlX2Ftb3VudGAgb2YgYHNvdXJjZV9hc3NldGAgaGFzIGJlZW4gcHVsbGVkIGludG8gZXNjcm93LgAAAAAABkZ1bmRlZAAAAAAAAQAAAHRUaGUgY29ycmlkb3IgcGlwZWxpbmUgaGFzIHBpY2tlZCB0aGUgcmVtaXR0YW5jZSB1cDsgb2ZmLWNoYWluCnNldHRsZW1lbnQgaXMgaW4gZmxpZ2h0IGFuZCB0aGUgc2VuZGVyIG1heSBub3QgY2FuY2VsLgAAAApQcm9jZXNzaW5nAAAAAAACAAAAflRoZSBzZXR0bGVtZW50IG9yYWNsZSBhdHRlc3RlZCB0aGF0IHRoZSBvZmYtY2hhaW4gcGF5b3V0IHdhcyBjb21wbGV0ZWQKZXhhY3RseSBhcyBjb21taXR0ZWQuIEZ1bmRzIGFyZSBwYXlhYmxlIHRvIGByZWNpcGllbnRgLgAAAAAAFFNldHRsZW1lbnRBdXRob3JpemVkAAAAAwAAAC1GdW5kcyAobmV0IG9mIGZlZXMpIHdlcmUgcGFpZCB0byBgcmVjaXBpZW50YC4AAAAAAAAIUmVsZWFzZWQAAAAEAAAAMlRoZSBmdWxsIGVzY3Jvd2VkIGFtb3VudCB3YXMgcmV0dXJuZWQgdG8gYHNlbmRlcmAuAAAAAAAIUmVmdW5kZWQAAAAFAAAAIURlcml2ZWQgb25seSDigJQgc2VlIG1vZHVsZSBkb2NzLgAAAAAAAAdFeHBpcmVkAAAAAAY=",
        "AAAAAgAAAbdTdG9yYWdlIGtleXMuCgpJbnN0YW5jZSBzdG9yYWdlIGNhcnJpZXMgY29udHJhY3QgY29uZmlndXJhdGlvbjogcm9sZXMsIHRoZSBnbG9iYWwgZmVlCmNvbmZpZyBhbmQgcGVyLWNvcnJpZG9yIHBhdXNlIGZsYWdzLiBUaG9zZSBtdXN0ICoqbmV2ZXIqKiBleHBpcmUgc2lsZW50bHkg4oCUCmEgY29ycmlkb3IgcGF1c2UgdGhhdCBhcmNoaXZlZCBpdHNlbGYgd291bGQgc2lsZW50bHkgcmUtZW5hYmxlIGEgY29ycmlkb3Ig4oCUCnNvIHRoZXkgbGl2ZSBpbiBpbnN0YW5jZSBzdG9yYWdlLCB3aGljaCBpcyByZS1leHRlbmRlZCBvbiBldmVyeSBtdXRhdGluZwpjYWxsLgoKUGVyc2lzdGVudCBzdG9yYWdlIGNhcnJpZXMgdGhlIHBlci1yZW1pdHRhbmNlIHJlY29yZHMgYW5kIHRoZSB0d28KbW9ub3RvbmljIGNvdW50ZXJzJyBtaXJyb3JzIHVzZWQgZm9yIGlkIGFsbG9jYXRpb24uAAAAAAAAAAAHRGF0YUtleQAAAAAIAAAAAAAAAAAAAAAFQWRtaW4AAAAAAAAAAAAAAAAAABBTZXR0bGVtZW50T3JhY2xlAAAAAAAAAAAAAAALRmVlT3BlcmF0b3IAAAAAAAAAAAAAAAAJRmVlQ29uZmlnAAAAAAAAAQAAAG9Db3JyaWRvciBpZGVudGlmaWVycyB0aGF0IGFyZSBhZG1pbmlzdHJhdGl2ZWx5IHBhdXNlZC4gQSBjb3JyaWRvciBpcwplbmFibGVkIGJ5IGRlZmF1bHQgdW5sZXNzIGl0IGFwcGVhcnMgaGVyZS4AAAAADlBhdXNlZENvcnJpZG9yAAAAAAABAAAADgAAAAAAAAAfTmV4dCByZW1pdHRhbmNlIGlkIHRvIGFsbG9jYXRlLgAAAAAGTmV4dElkAAAAAAAAAAAANFRvdGFsIHJlbWl0dGFuY2VzIGV2ZXIgY3JlYXRlZCAoaWRzIHJ1biBgMC4uY291bnRgKS4AAAAFQ291bnQAAAAAAAABAAAAAAAAAApSZW1pdHRhbmNlAAAAAAABAAAABg==",
        "AAAAAQAAAMxUaGUgZmVlIGNvbmZpZ3VyYXRpb24gaW4gZm9yY2UgZm9yIGEgc2luZ2xlIHJlbWl0dGFuY2UuCgpTbmFwc2hvdHRlZCBpbnRvIFtgUmVtaXR0YW5jZTo6ZmVlc2BdIGF0IGNyZWF0aW9uIHNvIHJlbGVhc2UgZmVlcyBhcmUKZGV0ZXJtaW5pc3RpYyBhbmQgYXVkaXRhYmxlIHJlZ2FyZGxlc3Mgb2YgbGF0ZXIgZ2xvYmFsIGNvbmZpZ3VyYXRpb24KY2hhbmdlcy4AAAAAAAAACUZlZUNvbmZpZwAAAAAAAAYAAABnT3B0aW9uYWwgYW5jaG9yL3BheW91dC1wcm92aWRlciBmZWUgaW4gYmFzaXMgcG9pbnRzLiBaZXJvIHdoZW4gdGhlCmNvcnJpZG9yIGhhcyBubyBzZXBhcmF0ZSBhbmNob3IgbGVnLgAAAAAKYW5jaG9yX2JwcwAAAAAABAAAADFUcmVhc3VyeSB0aGF0IHJlY2VpdmVzIHRoZSBhbmNob3IgZmVlIG9uIHJlbGVhc2UuAAAAAAAAD2FuY2hvcl90cmVhc3VyeQAAAAATAAAAJkNvcnJpZG9yL29wZXJhdG9yIGZlZSBpbiBiYXNpcyBwb2ludHMuAAAAAAAMY29ycmlkb3JfYnBzAAAABAAAADNUcmVhc3VyeSB0aGF0IHJlY2VpdmVzIHRoZSBjb3JyaWRvciBmZWUgb24gcmVsZWFzZS4AAAAAEWNvcnJpZG9yX3RyZWFzdXJ5AAAAAAAAEwAAADJQbGF0Zm9ybSBmZWUgaW4gYmFzaXMgcG9pbnRzICgxLzEwMCBvZiBhIHBlcmNlbnQpLgAAAAAADHBsYXRmb3JtX2JwcwAAAAQAAAAzVHJlYXN1cnkgdGhhdCByZWNlaXZlcyB0aGUgcGxhdGZvcm0gZmVlIG9uIHJlbGVhc2UuAAAAABFwbGF0Zm9ybV90cmVhc3VyeQAAAAAAABM=",
        "AAAAAQAAABpPbmUgcmVtaXR0YW5jZSBjb21taXRtZW50LgAAAAAAAAAAAApSZW1pdHRhbmNlAAAAAAAQAAAAJlRpbWUgdGhlIG9yYWNsZSBhdXRob3JpemVkIHNldHRsZW1lbnQuAAAAAAANYXV0aG9yaXplZF9hdAAAAAAAA+gAAAAGAAAAU0NvcnJpZG9yIGlkZW50aWZpZXIgKGUuZy4gYFVTRENfTkdOYCkuIFVzZWQgYnkgY29ycmlkb3IgcG9saWN5IGFuZApxdW90ZSBpbnRlZ3JpdHkuAAAAAAhjb3JyaWRvcgAAAA4AAAAdQ3JlYXRpb24gdGltZSAoVW5peCBzZWNvbmRzKS4AAAAAAAAKY3JlYXRlZF9hdAAAAAAABgAAAIdEZXN0aW5hdGlvbiBwYXlvdXQgY3VycmVuY3kvYXNzZXQgdGhlIG9yYWNsZSBtdXN0IGF0dGVzdCB0byAoZS5nLgpgTkdOYCkuIE9mZi1jaGFpbiBkZW5vbWluYXRpb24g4oCUIHNlZSBgZXhwZWN0ZWRfZGVzdGluYXRpb25fYW1vdW50YC4AAAAAEWRlc3RpbmF0aW9uX2Fzc2V0AAAAAAAADgAAAD1FeHBlY3RlZCBkZXN0aW5hdGlvbiBwYXlvdXQgYW1vdW50IHRoZSBvcmFjbGUgbXVzdCBhdHRlc3QgdG8uAAAAAAAAG2V4cGVjdGVkX2Rlc3RpbmF0aW9uX2Ftb3VudAAAAAALAAAAh0J1c2luZXNzIGV4cGlyeSAoVW5peCBzZWNvbmRzKS4gUXVvdGUgaW50ZWdyaXR5IGFuZCBjb3JyaWRvciBkZWFkbGluZXMKYXJlIGVuZm9yY2VkIGFnYWluc3QgdGhpcyB0aW1lc3RhbXA7IHN0b3JhZ2UgVFRMIGlzIGluZGVwZW5kZW50LgAAAAAGZXhwaXJ5AAAAAAAGAAAAOEltbXV0YWJsZSBmZWUgdGVybXMgdGhpcyByZW1pdHRhbmNlIHdhcyBjb21taXR0ZWQgdW5kZXIuAAAABGZlZXMAAAfQAAAACUZlZUNvbmZpZwAAAAAAAAAAAAAJZnVuZGVkX2F0AAAAAAAD6AAAAAYAAAAjTW9ub3RvbmljLCBuZXZlci1yZXVzZWQgaWRlbnRpZmllci4AAAAAAmlkAAAAAAAGAAAAhlNIQS0yNTYgY29tbWl0bWVudCB0byB0aGUgb2ZmLWNoYWluIHF1b3RlIHRoaXMgcmVtaXR0YW5jZSB3YXMgcHJpY2VkCmZyb20uIEJpbmRzIGF1dGhvcml6YXRpb24gdG8gdGhlIGV4YWN0IHF1b3RlIHRoZSBzZW5kZXIgYWNjZXB0ZWQuAAAAAAAKcXVvdGVfaGFzaAAAAAAD7gAAACAAAAB+VGhlIGFkZHJlc3MgdGhlIGVzY3Jvd2VkIGFzc2V0IGlzIHBhaWQgdG8gb24gcmVsZWFzZS4gRml4ZWQgYXQKY3JlYXRpb24g4oCUIHJlY2lwaWVudCBzdWJzdGl0dXRpb24gaXMgc3RydWN0dXJhbGx5IGltcG9zc2libGUuAAAAAAAJcmVjaXBpZW50AAAAAAAAEwAAAHJUaGUgcGFydHkgd2hvc2UgYXNzZXQgaXMgZXNjcm93ZWQuIFNpZ25zIHRoZSBjcmVhdGU7IHRoZSBvbmx5IHBhcnR5CnRoYXQgbWF5IGZ1bmQ7IHRoZSBvbmx5IHJlY2lwaWVudCBvZiBhIHJlZnVuZC4AAAAAAAZzZW5kZXIAAAAAABMAAAAsVGltZSBvZiByZWxlYXNlIG9yIHJlZnVuZCAodGVybWluYWwgZXZlbnRzKS4AAAAKc2V0dGxlZF9hdAAAAAAD6AAAAAYAAAB0R3Jvc3MgZXNjcm93ZWQgYW1vdW50LCBpbiBzdHJvb3BzLiBGZWVzIGFyZSBjYXJ2ZWQgb3V0IG9mIHRoaXMgYW1vdW50CmF0IHJlbGVhc2U7IHRoZSByZW1haW5kZXIgZ29lcyB0byBgcmVjaXBpZW50YC4AAAANc291cmNlX2Ftb3VudAAAAAAAAAsAAAA9U0VQLTQxIC8gU3RlbGxhciBBc3NldCBDb250cmFjdCB0b2tlbiBhZGRyZXNzIGJlaW5nIGVzY3Jvd2VkLgAAAAAAAAxzb3VyY2VfYXNzZXQAAAATAAAAAAAAAAZzdGF0dXMAAAAAB9AAAAAGU3RhdHVzAAA=",
        "AAAAAQAAAH1XaGF0IGByZWxlYXNlYCBwYWlkIG91dC4gUmV0dXJuZWQgc28gdGhlIGJhY2tlbmQgY2FuIHJlY29uY2lsZSB0aGUgZXNjcm93CnBheW91dCBsZWctYnktbGVnIHdpdGhvdXQgcmUtZGVyaXZpbmcgdGhlIGZlZSBtYXRoLgAAAAAAAAAAAAAOUmVsZWFzZVN1bW1hcnkAAAAAAAQAAAAAAAAACmFuY2hvcl9mZWUAAAAAAAsAAAAAAAAADGNvcnJpZG9yX2ZlZQAAAAsAAAAAAAAADHBsYXRmb3JtX2ZlZQAAAAsAAAAhTmV0IGFtb3VudCBwYWlkIHRvIHRoZSByZWNpcGllbnQuAAAAAAAAEHJlY2lwaWVudF9hbW91bnQAAAAL",
        "AAAABQAAABpBbiBhZG1pbiByb2xlIHdhcyByb3RhdGVkLgAAAAAAAAAAAAtSb2xlVXBkYXRlZAAAAAABAAAADHJvbGVfdXBkYXRlZAAAAAMAAAAAAAAAAmJ5AAAAAAATAAAAAQAAAAAAAAAEcm9sZQAAABEAAAABAAAAAAAAAANuZXcAAAAAEwAAAAAAAAAC",
        "AAAABQAAAElBIGZlZSB0cmVhc3VyeSBjaGFuZ2VkLiBgbGVnYCBpcyBvbmUgb2YgYHBsYXRmb3JtYCwgYGNvcnJpZG9yYCwgYGFuY2hvcmAuAAAAAAAAAAAAAA9UcmVhc3VyeVVwZGF0ZWQAAAAAAQAAABB0cmVhc3VyeV91cGRhdGVkAAAAAwAAAAAAAAACYnkAAAAAABMAAAABAAAAAAAAAANsZWcAAAAAEQAAAAEAAAAAAAAACHRyZWFzdXJ5AAAAEwAAAAAAAAAC",
        "AAAABQAAAEBGZWUgcmF0ZXMgY2hhbmdlZCAoYWZmZWN0cyBvbmx5IHJlbWl0dGFuY2VzIGNyZWF0ZWQgYWZ0ZXJ3YXJkcykuAAAAAAAAABBGZWVDb25maWdVcGRhdGVkAAAAAQAAABJmZWVfY29uZmlnX3VwZGF0ZWQAAAAAAAQAAAAAAAAAAmJ5AAAAAAATAAAAAQAAAAAAAAAMcGxhdGZvcm1fYnBzAAAABAAAAAAAAAAAAAAADGNvcnJpZG9yX2JwcwAAAAQAAAAAAAAAAAAAAAphbmNob3JfYnBzAAAAAAAEAAAAAAAAAAI=",
        "AAAABQAAAElgc291cmNlX2Ftb3VudGAgb2YgYHNvdXJjZV9hc3NldGAgd2FzIHB1bGxlZCBmcm9tIHRoZSBzZW5kZXIgaW50byBlc2Nyb3cuAAAAAAAAAAAAABBSZW1pdHRhbmNlRnVuZGVkAAAAAQAAABFyZW1pdHRhbmNlX2Z1bmRlZAAAAAAAAAUAAAAAAAAAAmlkAAAAAAAGAAAAAQAAAAAAAAAGc2VuZGVyAAAAAAATAAAAAQAAAAAAAAAMc291cmNlX2Fzc2V0AAAAEwAAAAEAAAAAAAAADXNvdXJjZV9hbW91bnQAAAAAAAALAAAAAAAAAAAAAAAJZnVuZGVkX2F0AAAAAAAABgAAAAAAAAAC",
        "AAAABQAAAJhBIHJlbWl0dGFuY2UgY29tbWl0bWVudCB3YXMgY3JlYXRlZC4gQ2FycmllcyB0aGUgY29tcGxldGUgaW5pdGlhbCBzdGF0ZSDigJQKdGhpcyBpcyB0aGUgZXZlbnQgYW4gaW5kZXhlciBidWlsZHMgaXRzIHNlbmRlci9yZWNpcGllbnQvcXVvdGUgbWFwcGluZwpmcm9tLgAAAAAAAAARUmVtaXR0YW5jZUNyZWF0ZWQAAAAAAAABAAAAEnJlbWl0dGFuY2VfY3JlYXRlZAAAAAAADgAAAAAAAAACaWQAAAAAAAYAAAABAAAAAAAAAAZzZW5kZXIAAAAAABMAAAABAAAAAAAAAAlyZWNpcGllbnQAAAAAAAATAAAAAQAAAAAAAAAMc291cmNlX2Fzc2V0AAAAEwAAAAAAAAAAAAAADXNvdXJjZV9hbW91bnQAAAAAAAALAAAAAAAAAAAAAAARZGVzdGluYXRpb25fYXNzZXQAAAAAAAAOAAAAAAAAAAAAAAAbZXhwZWN0ZWRfZGVzdGluYXRpb25fYW1vdW50AAAAAAsAAAAAAAAAAAAAAAhjb3JyaWRvcgAAAA4AAAAAAAAAAAAAAApxdW90ZV9oYXNoAAAAAAPuAAAAIAAAAAAAAAAAAAAABmV4cGlyeQAAAAAABgAAAAAAAAAAAAAACmNyZWF0ZWRfYXQAAAAAAAYAAAAAAAAAAAAAAAxwbGF0Zm9ybV9icHMAAAAEAAAAAAAAAAAAAAAMY29ycmlkb3JfYnBzAAAABAAAAAAAAAAAAAAACmFuY2hvcl9icHMAAAAAAAQAAAAAAAAAAg==",
        "AAAABQAAADRUaGUgZnVsbCBlc2Nyb3dlZCBhbW91bnQgd2FzIHJldHVybmVkIHRvIHRoZSBzZW5kZXIuAAAAAAAAABJSZW1pdHRhbmNlUmVmdW5kZWQAAAAAAAEAAAATcmVtaXR0YW5jZV9yZWZ1bmRlZAAAAAAFAAAAAAAAAAJpZAAAAAAABgAAAAEAAAAAAAAABnNlbmRlcgAAAAAAEwAAAAEAAAAAAAAADHNvdXJjZV9hc3NldAAAABMAAAAAAAAAAAAAAA9yZWZ1bmRlZF9hbW91bnQAAAAACwAAAAAAAAAAAAAAC3JlZnVuZGVkX2F0AAAAAAYAAAAAAAAAAg==",
        "AAAABQAAAEhUaGUgZXNjcm93IHdhcyBwYWlkIG91dDogZmVlcyB0byB0aGVpciB0cmVhc3VyaWVzLCBuZXQgdG8gdGhlIHJlY2lwaWVudC4AAAAAAAAAElJlbWl0dGFuY2VSZWxlYXNlZAAAAAAAAQAAABNyZW1pdHRhbmNlX3JlbGVhc2VkAAAAAAgAAAAAAAAAAmlkAAAAAAAGAAAAAQAAAAAAAAAJcmVjaXBpZW50AAAAAAAAEwAAAAEAAAAAAAAADHNvdXJjZV9hc3NldAAAABMAAAAAAAAAAAAAABByZWNpcGllbnRfYW1vdW50AAAACwAAAAAAAAAAAAAADHBsYXRmb3JtX2ZlZQAAAAsAAAAAAAAAAAAAAAxjb3JyaWRvcl9mZWUAAAALAAAAAAAAAAAAAAAKYW5jaG9yX2ZlZQAAAAAACwAAAAAAAAAAAAAACnNldHRsZWRfYXQAAAAAAAYAAAAAAAAAAg==",
        "AAAABQAAACFBIGNvcnJpZG9yIHdhcyBwYXVzZWQgb3IgcmVzdW1lZC4AAAAAAAAAAAAAFENvcnJpZG9yUGF1c2VDaGFuZ2VkAAAAAQAAABZjb3JyaWRvcl9wYXVzZV9jaGFuZ2VkAAAAAAADAAAAAAAAAAJieQAAAAAAEwAAAAEAAAAAAAAACGNvcnJpZG9yAAAADgAAAAEAAAAAAAAABnBhdXNlZAAAAAAAAQAAAAAAAAAC",
        "AAAABQAAAHFUaGUgc2V0dGxlbWVudCBvcmFjbGUgYXR0ZXN0ZWQgdGhlIGNvbW1pdHRlZCB0ZXJtcyB3ZXJlIGZ1bGZpbGxlZC4gVGhlCmVzY3JvdyBpcyBwYXlhYmxlIHRvIHRoZSBzdG9yZWQgcmVjaXBpZW50LgAAAAAAAAAAAAAUU2V0dGxlbWVudEF1dGhvcml6ZWQAAAABAAAAFXNldHRsZW1lbnRfYXV0aG9yaXplZAAAAAAAAAYAAAAAAAAAAmlkAAAAAAAGAAAAAQAAAAAAAAARc2V0dGxlbWVudF9vcmFjbGUAAAAAAAATAAAAAQAAAAAAAAAJcmVjaXBpZW50AAAAAAAAEwAAAAEAAAAAAAAADHNvdXJjZV9hc3NldAAAABMAAAAAAAAAAAAAAA1zb3VyY2VfYW1vdW50AAAAAAAACwAAAAAAAAAAAAAADWF1dGhvcml6ZWRfYXQAAAAAAAAGAAAAAAAAAAI=",
        "AAAABQAAAMZUaGUgY29ycmlkb3IgcGlwZWxpbmUgcGlja2VkIHRoZSBmdW5kZWQgcmVtaXR0YW5jZSB1cCBmb3Igb2ZmLWNoYWluCnNldHRsZW1lbnQuIEZyb20gdGhpcyBwb2ludCB0aGUgc2VuZGVyIGNhbm5vdCBjYW5jZWw7IG9ubHkgZXhwaXJ5LCBhbgphZG1pbiByZWZ1bmQgb3IgYW4gb3JhY2xlIGF1dGhvcml6YXRpb24gcmVzb2x2ZXMgdGhlIGVzY3Jvdy4AAAAAAAAAAAAbUmVtaXR0YW5jZVByb2Nlc3NpbmdTdGFydGVkAAAAAAEAAAAdcmVtaXR0YW5jZV9wcm9jZXNzaW5nX3N0YXJ0ZWQAAAAAAAADAAAAAAAAAAJpZAAAAAAABgAAAAEAAAAAAAAAEXNldHRsZW1lbnRfb3JhY2xlAAAAAAAAEwAAAAEAAAAAAAAACnN0YXJ0ZWRfYXQAAAAAAAYAAAAAAAAAAg==" ]),
      options
    )
  }
  public readonly fromJSON = {
    refund: this.txFromJSON<Result<i128>>,
        release: this.txFromJSON<Result<ReleaseSummary>>,
        version: this.txFromJSON<u32>,
        get_admin: this.txFromJSON<Result<string>>,
        set_admin: this.txFromJSON<Result<void>>,
        status_of: this.txFromJSON<Result<Status>>,
        initialize: this.txFromJSON<Result<void>>,
        is_expired: this.txFromJSON<Result<boolean>>,
        set_fee_bps: this.txFromJSON<Result<void>>,
        get_fee_config: this.txFromJSON<Result<FeeConfig>>,
        get_remittance: this.txFromJSON<Result<Remittance>>,
        fund_remittance: this.txFromJSON<Result<void>>,
        begin_processing: this.txFromJSON<Result<void>>,
        get_fee_operator: this.txFromJSON<Result<string>>,
        remittance_count: this.txFromJSON<u64>,
        set_fee_operator: this.txFromJSON<Result<void>>,
        set_fee_treasury: this.txFromJSON<Result<void>>,
        create_remittance: this.txFromJSON<Result<u64>>,
        is_corridor_paused: this.txFromJSON<boolean>,
        set_corridor_paused: this.txFromJSON<Result<void>>,
        authorize_settlement: this.txFromJSON<Result<void>>,
        extend_remittance_ttl: this.txFromJSON<Result<u32>>,
        get_settlement_oracle: this.txFromJSON<Result<string>>,
        set_settlement_oracle: this.txFromJSON<Result<void>>
  }
}